print ('Hello! Welcome to my Mad Lib game :)')
print ('Hope you enjoy!')
print ()
print ('To begin, please fill out the following: ')
print ()
# setting the variable values
adjective_1 = input ('Adjective: ')
verb_1 = input ('V1 Verb: ')
animal = input ('Animal: ')
verb_2 = input ('V1 Verb: ')
exclamation_1 = input ('Exclamation: ')
verb_3 = input ('V1 Verb: ')
adjective_2 = input ('Adjective: ')
instrument = input ('Musical instrument: ')
spt_verb = input ('Simple past tense verb: ')
exclamation_2 = input ('Exclamation: ')
print ()
# the slightly altered story with variables
print (f'The other day, I was really in trouble. It all started when I saw a very {adjective_1.lower()} {animal.lower()} {verb_1.lower()} down the hallway. "{exclamation_1.capitalize()}!" I yelled. But all I could think to do was to {verb_2.lower()} over and over. Miraculously, that caused it to stop, but not before it tried to {verb_3.lower()} right in front of my family. The whole thing made me very {adjective_2.lower()}, so I decided to play my {instrument.lower()}. This made the {animal.lower()} go crazy! I panicked and {spt_verb.lower()} my {instrument.lower()} on the floor. "{exclamation_2.capitalize()}!" Said the {animal.lower()} and shook its head.')