print('Hey there!')
print()
print('What should I call you?')
print()
name = input('My name is: ')
print()
print(f'Hello, {name}! Nice to meet you.')
print()
print('We should get to know each other a bit better.')
print()
print('What is your favorite drink?')
print()
drink = input('My favorite drink is: ')
print()
print(f'Wow, really?! I love {drink} too!')
print()
print('What about your favorite color?')
print()
color = input('Please type your answer here: ')
print()
print(f'No way! {name} and I both like {drink} and {color}?!')
print()
print('What a crazy coincidence!')